spring:
  rabbitmq:
    host: 192.168.43.164
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        ##auto自动签收 manual手动签收
        acknowledge-mode: manual
        max-concurrency: 10
        ##(限流 逐条消费)
        prefetch: 1
server:
  port: 9090